services:
  app:
    image: waleedabdulhadi/chat-server:latest
    build:
      context: .
      # dockerfile: Dockerfile
      args:
        SERVER_URL: ${SERVER_URL}
    container_name: chatapp-server
    environment:
      SERVER_URL: ${SERVER_URL}
      SERVICE_URI: ${SERVICE_URI}
      JWT_SECRET: ${JWT_SECRET}
      db_name: ${db_name}
      db_host: db
      db_port: ${db_port}
      db_username: ${db_username}
      db_password: ${db_password}
    depends_on:
      - db
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    networks:
      - chat-net

  db:
    image: mariadb:latest
    container_name: local-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${db_password}
      MARIADB_DATABASE: ${db_name}
      MARIADB_USER: ${db_username}
      MARIADB_PASSWORD: ${db_password}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - chat-net

volumes:
  mariadb_data:

networks:
  chat-net:
    driver: bridge
